# Generated by Django 3.2.10 on 2024-04-03 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Product_Image', models.ImageField(upload_to='product_images')),
                ('Product_Image2', models.ImageField(null=True, upload_to='product_images')),
                ('Product_Image3', models.ImageField(null=True, upload_to='product_images')),
                ('Product_Image4', models.ImageField(null=True, upload_to='product_images')),
                ('Product_Image5', models.ImageField(null=True, upload_to='product_images')),
                ('Gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('boy', 'Boy'), ('girl', 'Girl')], max_length=10)),
                ('Category', models.CharField(choices=[('shirts', 'Shirts'), ('pants', 'Pants'), ('shoes', 'Shoes'), ('accessories', 'Accessories')], max_length=20)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('Offer_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Size1', models.CharField(default='', max_length=10)),
                ('Size2', models.CharField(default='', max_length=10)),
                ('Size3', models.CharField(default='', max_length=10)),
                ('Size4', models.CharField(default='', max_length=10)),
                ('Size5', models.CharField(default='', max_length=10)),
                ('Color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp_secret_key', models.CharField(blank=True, max_length=32, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='passwordresetuser_set', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='passwordresetuser_set', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('password2', models.CharField(default='********', max_length=200)),
                ('mobile', models.IntegerField(null=True, unique=True)),
                ('otp', models.CharField(blank=True, max_length=32, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=200, null=True, unique=True)),
                ('otp_secret_key', models.CharField(blank=True, max_length=32, null=True)),
                ('address1', models.CharField(blank=True, max_length=250, null=True)),
                ('address2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
