# Generated by Django 3.2.10 on 2024-04-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Product_Image',
            new_name='Product_Images',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Size1',
            new_name='Size',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Product_Image2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Product_Image3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Product_Image4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Product_Image5',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Size2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Size3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Size4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Size5',
        ),
    ]
