# Generated by Django 3.2.10 on 2024-04-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240403_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Product_Images',
            new_name='Product_Image1',
        ),
        migrations.AddField(
            model_name='products',
            name='Product_Image2',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='products',
            name='Product_Image3',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='products',
            name='Product_Image4',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='products',
            name='Product_Image5',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
