# Generated by Django 3.2.10 on 2024-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240403_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Size',
            new_name='Size1',
        ),
        migrations.AddField(
            model_name='products',
            name='Size2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='Size3',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='Size4',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='Size5',
            field=models.CharField(default='', max_length=10),
        ),
    ]
