# Generated by Django 3.2.10 on 2024-04-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_pincodecitymapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PincodeCityMapping',
        ),
    ]
