# Generated by Django 3.2.10 on 2024-04-12 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
