# Generated by Django 3.2.10 on 2024-04-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20240413_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='default', max_length=100),
        ),
        
    ]
