# Generated by Django 3.2.10 on 2024-04-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
    ]
