# Generated by Django 3.2.10 on 2024-04-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_image1',
            field=models.ImageField(null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
